name: GenderEx Live
on: workflow_dispatch
jobs:
  genderex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install GenderEx
        run: pip install spotify-gender-ex
      
      - uses: actions/checkout@v2
      
      - name: Copy Keystore
        run: mkdir ./GenderEx && cp ${{ github.workspace }}/genderex.keystore ./GenderEx/
      
      - name: Run GenderEx
        run: spotify-gender-ex --noia --kspw '${{ secrets.KEYSTORE_PASSWORD }}' --kypw '${{ secrets.KEY_PASSWORD }}'
      
      - name: Store app
        uses: actions/upload-artifact@v2
        with:
          name: spotify-app
          path: ./GenderEx/output/*
          retention-days: 7
