name: Dispatch GenderEx

on:
  push:
    branches:
      - master
    paths:
      - 'spotify_gender_ex/res/replacements.json'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test replacements
        run: pytest tests/test_replacements.py

      - name: Run GenderEx
        run: |
          echo "${{ secrets.TRIGGER_SSH_KEY }}" > ssh_key
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh_key trigger@thetadev.de
          rm ssh_key
