name: Dispatch GenderEx

on:
  push:
    branches:
      - master
    paths:
      - 'spotify_gender_ex/res/replacements.json'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test replacements
        run: pytest tests/test_replacements.py

      - name: Run GenderEx
        run: |
          mkdir ~/.ssh
          echo "thetadev.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOENIbF43EQi41ndBcnDIr9EMOSesx/KW+FufnkzPhRH" > ~/.ssh/known_hosts
          echo "${{ secrets.TRIGGER_SSH_KEY }}" > ~/.ssh/id_ed25519
          ssh trigger@thetadev.de
          rm -rf ~/.ssh
